name: iGates
main: com.ptibiscuit.igates.Plugin
version: 0.6.2-adam
depend: [PluginsBaker]
softdepend: [Multiverse-Core]
authors:
- Ptibiscuit
commands:
 igcreate:
  description: Cree un portail.
  usage: /igcreate <Tag> <FillType>
 igset:
  description: Cree un portail.
  usage: /igset ...
 igdelete:
  description: Cree un portail.
  usage: /igdelete ...
 igaddfrom:
  description: Cree un portail.
  usage: /igaddfrom ...
 iglist:
  description: Liste les portails.
  usage: /iglist
 igclearfroms:
  description: ...
  usage: /igclearfroms ...
 igdump:
  description: ...
  usage: /igdump ...
  